#!/bin/bash

XUBAPPINIT=/usr/share/xubapp/xubapp
XUBAPPAVS=/usr/share/xubapp/xubapp-avs
XUBAPPPNC=/usr/share/xubapp/xubapp.sh
XUBAPPADG=/usr/share/xubapp/xubapp-addrepgpg
XUBAPPCP=/usr/share/xubapp/xubapp-compilacoes
XUBAPPMT=/usr/share/xubapp/xubapp-multimedia
XUBAPPOPT=/usr/share/xubapp/xubapp-opcional
XUBAPPUPG=/usr/share/xubapp/xubapp-upgrade
XUBAPPHLP=/usr/share/xubapp/xubapp-hlp
CXUBAG=/var/cache/xubapp-ag
CXUBUPG=/var/cache/xubapp-upg
CXUBCM=/var/cache/xubapp-cm
CXUBMC=/var/cache/xubapp-mc
CXUBOP=/var/cache/xubapp-op
CREPGPG=/var/cache/addgpg

case $1 in

--start|-s)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPAVS ]
			then
	sudo sh -c 'echo -e ""' > $CREPGPG
	$XUBAPPAVS
	clear
			else
	echo -e 'Nao foi possivel acessar o aplicativo xubapp!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

--start-menu|-sm)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPPNC ]
			then
	sudo sh -c 'echo -e ""' > $CREPGPG
	$XUBAPPPNC
	clear
			else
	echo -e 'Nao foi possivel acessar o menu principal!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

--add-rep|-ar)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPADG ]
			then
	sudo sh -c 'echo -e "xubapp-addrepgpg-menu-off"' > $CXUBAG
	$XUBAPPADG
	clear
			else
	echo -e 'Nao foi possivel acessar adicao de repositorios!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

--upgrade|-u)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPUPG ]
			then
	sudo sh -c 'echo -e "xubapp-upgrade-menu-off"' > $CXUBUPG
	$XUBAPPUPG
	clear
			else
	echo -e 'Nao foi possivel acessar upgrade!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

--compilers-maintenance|-cm)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPCP ]
			then
	sudo sh -c 'echo -e ""' > $CXUBCM
	$XUBAPPCP
	clear
			else
	echo -e 'Nao foi possivel acessar o menu de compiladores e manutencao!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

--multimedia-codecs|-mc)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPMT ]
			then
	sudo sh -c 'echo -e ""' > $CXUBMC
	$XUBAPPMT
	clear
			else
	echo -e 'Nao foi possivel acessar o menu multimedia e codecs!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

--optional-applications|-o)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPOPT ]
			then
	sudo sh -c 'echo -e ""' > $CXUBOP
	$XUBAPPOPT
	clear
			else
	echo -e 'Nao foi possivel acessar o menu opcional!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

--help|-h)
if [ -e $XUBAPPINIT ]
		then
if [ -e $XUBAPPHLP ]
			then
	cat $XUBAPPHLP
			else
	echo -e 'Nao foi possivel acessar o menu help!'
	echo -e 'Saindo do configurador...'
	read -t 3
	exit 0
fi
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;

  *)
	clear
if [ -e $XUBAPPINIT ]
		then
	echo -e 'Deve usar as opcoes:
		xubapp {start|--start-menu|--add-rep|--upgrade|--compilers-maintenance|--multimedia-codecs|--optional-applications|--help|-h}'
		else
	echo -e 'Servico xubapp indisponivel!'
fi
	;;
esac





