#!/bin/bash

XUBAPPINIT=/usr/share/xubapp/xubapp
XUBAPPAVS=/usr/share/xubapp/xubapp-avs
XUBAPPPNC=/usr/share/xubapp/xubapp.sh
XUBAPPADG=/usr/share/xubapp/xubapp-addrepgpg
XUBAPPCP=/usr/share/xubapp/xubapp-compilacoes
XUBAPPMT=/usr/share/xubapp/xubapp-multimedia
XUBAPPOPT=/usr/share/xubapp/xubapp-opcional
XUBAPPUPG=/usr/share/xubapp/xubapp-upgrade
CXUBAG=/var/cache/xubapp-ag
CXUBUPG=/var/cache/xubapp-upg
CXUBCM=/var/cache/xubapp-cm
CXUBMC=/var/cache/xubapp-mc
CXUBOP=/var/cache/xubapp-op
CREPGPG=/var/cache/addgpg

if [ -e $XUBAPPINIT ]
		then
###Inicio Adicionar
##Adicionar(){
if [ -e $CXUBAG ]
			then
#	clear
#	echo -e '\n Adicionar repositorios...'
#	echo -e '\b Espere 30 segundos ou aperte "Enter".'
#	read -t 30
#Oracle VM VirtualBox
sudo sh -c 'touch /etc/apt/sources.list.d/virtualbox.list'
sudo sh -c 'rm -rf /etc/apt/sources.list.d/virtualbox.list'
sudo sh -c 'touch /etc/apt/sources.list.d/virtualbox.list'
sudo sh -c 'cat > /etc/apt/sources.list.d/virtualbox.list' <<EOF
#Oracle VM VirtualBox
deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib non-free
EOF
wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 54422A4B98AB5139
#Depôt MultiSystem
sudo sh -c 'touch /etc/apt/sources.list.d/multisystem.list'
sudo sh -c 'cat > /etc/apt/sources.list.d/multisystem.list' <<EOF
#Depôt MultiSystem, Criador multiboot usb
deb http://liveusb.info/multisystem/depot all main
EOF
wget -q http://liveusb.info/multisystem/depot/multisystem.asc -O- | sudo apt-key add -
##Google-chrome:
sudo sh -c 'touch /etc/apt/sources.list.d/google-chrome.list'
sudo sh -c 'rm -rf /etc/apt/sources.list.d/google-chrome.list'
sudo sh -c 'touch /etc/apt/sources.list.d/google-chrome.list'
sudo sh -c 'cat > /etc/apt/sources.list.d/google-chrome.list' <<EOF
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb http://dl.google.com/linux/chrome/deb/ stable main
EOF
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
##google-talkplugin_current:
sudo sh -c 'touch /etc/apt/sources.list.d/google-talkplugin.list'
sudo sh -c 'rm -rf /etc/apt/sources.list.d/google-talkplugin.list'
sudo sh -c 'touch /etc/apt/sources.list.d/google-talkplugin.list'
sudo sh -c 'cat > /etc/apt/sources.list.d/google-talkplugin.list' <<EOF
### THIS FILE IS AUTOMATICALLY CONFIGURED ###
# You may comment out this entry, but any other modifications may be lost.
deb http://dl.google.com/linux/talkplugin/deb/ stable main
EOF
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#zram
#sudo add-apt-repository -y ppa:shnatsel/zram
#zram quantal saucy trusty
#if (lsb_release -cs | grep -i quantal)
#		then
#sudo sed -i "s/$(lsb_release -cs)/quantal/g" /etc/apt/sources.list.d/shnatsel-zram-$(lsb_release -cs).list
#	else
#if (lsb_release -cs | grep -i saucy)
#		then
#sudo sed -i "s/$(lsb_release -cs)/quantal/g" /etc/apt/sources.list.d/shnatsel-zram-$(lsb_release -cs).list
#	else
#	if (lsb_release -cs | grep -i trusty)
#		then
#sudo sed -i "s/$(lsb_release -cs)/quantal/g" /etc/apt/sources.list.d/shnatsel-zram-$(lsb_release -cs).list
#	else
#	echo -e 'Repositório zram OK!'
#fi
#fi
#fi

#sysmonitor no unity
#sudo add-apt-repository -y ppa:alexeftimie/ppa
##sysmonitor saucy trusty
#if (lsb_release -cs | grep -i saucy)
#		then
#sudo sed -i "s/$(lsb_release -cs)/raring/g" /etc/apt/sources.list.d/alexeftimie-ppa-$(lsb_release -cs).list
#	else
#if (lsb_release -cs | grep -i trusty)
#		then
#sudo sed -i "s/$(lsb_release -cs)/raring/g" /etc/apt/sources.list.d/alexeftimie-ppa-$(lsb_release -cs).list
#	else
#	echo -e 'Repositório sysmonitor OK!'
#fi
#fi

#remastersys (programa para bkp do sistema e criação de livecd atraves do sistema instalado)
#wget -q http://www.remastersys.com/ubuntu/remastersys.gpg.key -O- | sudo apt-key add -
#sudo sh -c 'touch /etc/apt/sources.list.d/remastersys.list'
#sudo sh -c 'rm -rf /etc/apt/sources.list.d/remastersys.list'
#sudo sh -c 'touch /etc/apt/sources.list.d/remastersys.list'
#sudo echo 'deb http://www.remastersys.com/ubuntu precise main' >> /etc/apt/sources.list.d/remastersys.list

#ubuntu cambrium
if (lsb_release -cs | grep -i precise)
	then
sudo sh -c 'touch /etc/apt/sources.list.d/ub-cambrium.list'
sudo sh -c 'rm -rf /etc/apt/sources.list.d/ub-cambrium.list'
sudo sh -c 'touch /etc/apt/sources.list.d/ub-cambrium.list'
sudo sh -c 'cat > /etc/apt/sources.list.d/ub-cambrium.list' <<EOF
#precise universe, para dependencias libx264-120 e outros
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs) main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-backports main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-proposed main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-security main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-updates main universe multiverse restricted
EOF
else
sudo sh -c 'touch /etc/apt/sources.list.d/ub-cambrium.list'
sudo sh -c 'rm -rf /etc/apt/sources.list.d/ub-cambrium.list'
sudo sh -c 'touch /etc/apt/sources.list.d/ub-cambrium.list'
sudo sh -c 'cat > /etc/apt/sources.list.d/ub-cambrium.list' <<EOF
#precise universe, para dependencias libx264-120 e outros
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ precise main universe
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs) main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-backports main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-proposed main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-security main universe multiverse restricted
deb http://ubuntu.mirror.cambrium.nl/ubuntu/ $(lsb_release -cs)-updates main universe multiverse restricted
EOF
fi
#Ubuntu games (tem o Kega-Fusion) - (Repositório fora do ar)
#sudo rm -rf /etc/apt/sources.list.d/ubuntugames.list
#sudo echo 'deb http://archive.ubuntugames.org ubuntugames main' >> /etc/apt/sources.list.d/ubuntugames.list ;
#sudo echo 'deb-src http://archive.ubuntugames.org ubuntugames main' >> /etc/apt/sources.list.d/ubuntugames.list ;
#wget -q -O - http://archive.ubuntugames.org/ubuntugames.key | sudo apt-key add -

## Repositorio de games Playdeb
#	http://www.playdeb.net
sudo mkdir -p /var/cache/apt/archives
cd /var/cache/apt/archives
sudo wget -c http://archive.getdeb.net/install_deb/playdeb_0.3-1~getdeb1_all.deb -P /var/cache/apt/archives
sudo dpkg -i playdeb_0.3-1~getdeb1_all.deb
cd -

#Wine
sudo add-apt-repository -y ppa:ubuntu-wine/ppa
#Oracle Java Development Kit
sudo add-apt-repository -y ppa:webupd8team/java
#medibuntu (videolan)
	if (ls /etc/apt/sources.list.d |grep -i "medibuntu.list")
		then
			sudo rm -rf /etc/apt/sources.list.d/medibuntu.list
			echo 'Removido repositorio medibuntu...'
			echo 'Adicionando repositorio videolan...'
		else
			echo 'Adicionando repositorio videolan...'
	fi
	if (ls /etc/apt/sources.list.d |grep -i "libdvdcss.list")
		then
			sudo rm -rf /etc/apt/sources.list.d/libdvdcss.list
			echo 'Removido repositorio libdvdcss...'
			echo 'Adicionando repositorio videolan...'
		else
			echo 'Adicionando repositorio videolan...'
	fi
#sudo touch /etc/apt/sources.list.d/libdvdcss.list
#sudo rm -rf /etc/apt/sources.list.d/libdvdcss.list
#sudo touch /etc/apt/sources.list.d/libdvdcss.list
#sudo sh -c "echo 'deb http://download.videolan.org/pub/debian/stable/ /' >> /etc/apt/sources.list.d/libdvdcss.list"
#sudo sh -c "echo 'deb-src http://download.videolan.org/pub/debian/stable/ /' >> /etc/apt/sources.list.d/libdvdcss.list"
#wget -O - http://download.videolan.org/pub/debian/videolan-apt.asc | sudo apt-key add -
#
## VLC 2.2.x para cima
sudo add-apt-repository -y ppa:videolan/stable-daily
## Fim VLC 2.2.x para cima
## VLC 3.x.x para cima
# sudo add-apt-repository -y ppa:videolan/master-daily
## Fim VLC 3.x.x para cima
## Flash Current para o Firefox
sudo apt-add-repository -y ppa:pipelight/stable
## Fim do Flash
#sudo add-apt-repository -y ppa:videolan/master-daily
##	Repositorio PlayOnLinux
if (lsb_release -cs | grep -i precise)
	then
sudo rm -rf /etc/apt/sources.list.d/playonlinux.list >> /dev/null
wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
sudo wget http://deb.playonlinux.com/playonlinux_$(lsb_release -cs).list -O /etc/apt/sources.list.d/playonlinux.list
else
if (lsb_release -cs | grep -i trusty)
	then
sudo rm -rf /etc/apt/sources.list.d/playonlinux.list >> /dev/null
wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
sudo wget http://deb.playonlinux.com/playonlinux_$(lsb_release -cs).list -O /etc/apt/sources.list.d/playonlinux.list
else
if (lsb_release -cs | grep -i utopic)
	then
sudo rm -rf /etc/apt/sources.list.d/playonlinux.list >> /dev/null
wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
sudo wget http://deb.playonlinux.com/playonlinux_$(lsb_release -cs).list -O /etc/apt/sources.list.d/playonlinux.list
else
if (lsb_release -cs | grep -i vivid)
	then
sudo rm -rf /etc/apt/sources.list.d/playonlinux.list >> /dev/null
wget -q "http://deb.playonlinux.com/public.gpg" -O- | sudo apt-key add -
sudo wget http://deb.playonlinux.com/playonlinux_$(lsb_release -cs).list -O /etc/apt/sources.list.d/playonlinux.list
else
if (ls /etc/apt/sources.list.d | grep -i playonlinux.list)
			then
	echo -e "\n\nRepositorio PlayonLinux Ok!"
		else
	echo -e "\n\nRepositorio PlayonLinux nao foi criado!"
		sleep 5
fi
fi
fi
fi
fi
##	Fim Repositorio PlayOnLinux

## Repositorio Gnomebaker
sudo add-apt-repository -y ppa:gnomebaker/stable
sudo sed -i "s/$(lsb_release -cs)/precise/g" /etc/apt/sources.list.d/gnomebaker-stable-$(lsb_release -cs).list
## Fim Repositorio GnomeBaker
## Repositorio youtube-dl
sudo add-apt-repository -y ppa:nilarimogard/webupd8
##Fim Repositorio youtube-dl
clear
	echo -e '\n Atualizando os repositorios...'
	echo -e '\b Aguarde 30 Segundos ou aperte "Enter".'
read -t 30
#Prevenir erro "BADSIG ID"
#Inicio
sudo -i apt-get -y clean
sudo -i apt-get -y autoclean
cd /var/lib/apt

#list.old	
if (ls /var/lib/apt | grep -i lists.old)
			then
		sudo -i rm -rf /var/lib/apt/lists.old
#list1
	if (ls /var/lib/apt | grep -i lists)
			then
		sudo -i mv /var/lib/apt/lists /var/lib/apt/lists.old
		sudo -i mkdir -p  /var/lib/apt/lists/partial
			else
		sudo -i mkdir -p  /var/lib/apt/lists/partial
	fi
#list1fim
			else
#list2
	if (ls /var/lib/apt | grep -i lists)
			then
		sudo -i mv /var/lib/apt/lists /var/lib/apt/lists.old
		sudo -i mkdir -p  /var/lib/apt/lists/partial
			else
		sudo -i mkdir -p  /var/lib/apt/lists/partial
	fi
#listfim2
fi
#list.oldfim

cd -

sudo -i apt-get -y clean
sudo -i apt-get -y autoclean
sudo -i apt-get -y update
#Fim
#Fim "BADSIG ID"
clear
#	echo -e '\n Verificando e fazendo upgrade do sistema...'
#	echo -e '\b Aguarde 30 Segundos ou aperte "Enter".'
#read -t 30
#sudo apt-get -y dist-upgrade
#read -t 10
#clear
if ( cat $CXUBAG | grep "xubapp-addrepgpg-menu-off" | sed -n 1p )
			then
	read -t 3
	exit 0

else
	echo -e '\n Configuracao dos repositorios terminada.'
#	echo -e '\b Indo para a proxima etapa'
	echo -e "Voltando ao menu principal..."
	echo -e '\b Aguarde 30 Segundos ou aperte "Enter".'
read -t 30
#	ConfInstall
	$XUBAPPPNC
fi
			else
clear
echo -e "Nao ha como executar esta acao!"
echo -e "Voltando ao menu principal..."
read -t 30
$XUBAPPPNC
fi
##}
###Fim Adicionar
		else
	echo -e 'Servico xubapp indisponivel!'
fi
